---
# tasks file for ajsalminen.drupal_basic

- name: Set wp_local_site_name
  set_fact:
    wp_local_site_name: "{{ site_name ~ local_test_environment|default('') }}"
  when: site_name != '000-default'

- name: Replace site name
  shell: /usr/local/bin/wp --allow-root search-replace --skip-columns=guid --url={{wordpress_db.site_name}} {{wordpress_db.site_name}} {{wp_local_site_name}} chdir={{wordpress_webroot}}
  when: wp_present.stat.exists == false and wordpress_db.site_name is defined and wordpress_db.site_name != wp_local_site_name